version: '3.3'

services:
  app:
    build: .
    container_name: springboot-app
    ports:
      - "8889:8888"
    volumes:
      # Mount the Tomcat configuration files
      - ./tomcat-conf/server.xml:/usr/local/tomcat/conf/server.xml
      - ./tomcat-conf/context.xml:/usr/local/tomcat/conf/context.xml
    environment:
      SPRING_PROFILES_ACTIVE: "default"
    networks:
      - app-network

  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: kernelExtPicoSoft
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql
    ports:
      - "5433:5432"
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
