version: '3.8'

services:
  postgres:
    image: postgres:15.4
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql
      POSTGRES_DB: kernelExtPicoSoft
    ports:
      - "10181:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: springboot_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kernelExtPicoSoft
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: psql
    ports:
      - "8081:8081"
    depends_on:
      - postgres

volumes:
  postgres_data:
